### ISSUE TITLE
website should address ubuntu only

### ISSUE THREAD

**Issue by ian-kelling** [anbox/anbox.github.com#4]
running anbox-installer, 

    ERROR: You are running the installer on a not support distribution.
           At the moment we only support Ubuntu.

"Run Android applications on any GNU Linux operating system.", ok I understand that is the goal and the tag line, but in the getting started, before I actually run things, it should address the fact that the installer will directly contradict that statement.

**Comment by morphis** [comment]
Not valid anymore.
