### ISSUE TITLE
Update website for installing apk's

### ISSUE THREAD

**Issue by salarelv** [anbox/anbox.github.com#6]
1. Enable installing from unknown sources from settings.
2. Downloading f-droid from f-droid.org.
3. Install F-Droid with adb install FDroid.apk.

**Comment by salarelv** [comment]
Maybe it is possible to bundle f-droid in the installation

**Comment by morphis** [comment]
Please see my comment on https://github.com/anbox/anbox/issues/27#issuecomment-293486105
